-- CreateTable
CREATE TABLE "Pal1" (
    "id" SERIAL NOT NULL,
    "time_id" INTEGER NOT NULL,
    "openingStock" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "openingStockValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "purchaseRm" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "purchaseRmValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "purchaseTrading" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "purchaseTradingValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "purchaseConsumables" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "purchaseConsumablesValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "closingStock" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "closingStockValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "sales" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "salesValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "waste" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "wasteValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "otherInc" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "directExpenses" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "inHouseFabricationQty" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "inHouseFabricationValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "fabricationQty" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "fabricationValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "deprecation" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "indirectExpenses" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "directCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "ProfitA" DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT "Pal1_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Pal1_time_id_key" ON "Pal1"("time_id");
