-- AlterTable
ALTER TABLE "TradingPl" ADD COLUMN     "Cost_Of_Sales_Qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "Cost_Of_Sales_Value" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "Direct_Expenses_Value" DOUBLE PRECISION NOT NULL DEFAULT 0;
